package jmc.skweb.core.model;

// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArtMadre generated by hbm2java
 */
@Entity
//@Table(name = "ArtMadre", schema = "ComunSql.dbo")
//@Table(name = "ArtMadre", schema = "ArtPlas.dbo")
@Table(name = "ArtMadre", schema = "ComunSql.dbo")
public class ArtMadre implements java.io.Serializable {

	private String codArtMad;
	private String descArtMad;
	private String obser;
	private List<Stock> articulosHijos = new ArrayList<Stock>();

	public ArtMadre() {
	}

	public ArtMadre(String codArtMad) {
		this.codArtMad = codArtMad;
	}

	public ArtMadre(String codArtMad, String descArtMad, String obser) {
		this.codArtMad = codArtMad;
		this.descArtMad = descArtMad;
		this.obser = obser;
	}

	@Id
	@Column(name = "CodArtMad", unique = true, nullable = false, length = 13)
	public String getCodArtMad() {
		return this.codArtMad;
	}

	public void setCodArtMad(String codArtMad) {
		this.codArtMad = codArtMad;
	}

	@Column(name = "DescArtMad", length = 50)
	public String getDescArtMad() {
		return this.descArtMad;
	}

	public void setDescArtMad(String descArtMad) {
		this.descArtMad = descArtMad;
	}

	@Column(name = "Obser", length = 200)
	public String getObser() {
		return this.obser;
	}

	public void setObser(String obser) {
		this.obser = obser;
	}

	@OneToMany(cascade=CascadeType.ALL,targetEntity=Stock.class,fetch=FetchType.LAZY,mappedBy="artMadre")
	public List<Stock> getArticulosHijos() {
		return articulosHijos;
	}

	public void setArticulosHijos(List<Stock> articulosHijos) {
		this.articulosHijos = articulosHijos;
	}

	
}
