package jmc.skweb.core.model;

// Generated 22/09/2011 00:18:30 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * DetaViajes generated by hbm2java
 */
@Entity
@Table(name = "DetaViajes", schema = "")
public class DetaViajes implements java.io.Serializable {

	private byte[] unico;
	private Viajes viajes;
	private Transac transacRemito;
	private Integer expreso;
	private String localidad;
	private Date horaSalida;
	private Date horaEntrada;
	private String obser;
	private Integer noCalcula;
	private Float bultos;
	private Float cant1;
	private Float cant2;
	private Integer orden;
	private BigDecimal netoGrav;

	public DetaViajes() {
	}

	public DetaViajes(byte[] unico, Viajes viajes) {
		this.unico = unico;
		this.viajes = viajes;
	}

	public DetaViajes(byte[] unico, Viajes viajes, Integer transacRemito,
			Integer expreso, String localidad, Date horaSalida,
			Date horaEntrada, String obser, Integer noCalcula, Float bultos,
			Float cant1, Float cant2, Integer orden, BigDecimal netoGrav) {
		this.unico = unico;
		this.viajes = viajes;
		
		this.expreso = expreso;
		this.localidad = localidad;
		this.horaSalida = horaSalida;
		this.horaEntrada = horaEntrada;
		this.obser = obser;
		this.noCalcula = noCalcula;
		this.bultos = bultos;
		this.cant1 = cant1;
		this.cant2 = cant2;
		this.orden = orden;
		this.netoGrav = netoGrav;
	}

	@Id
	@Column(name = "unico", unique = true, nullable = false)
	public byte[] getUnico() {
		return this.unico;
	}

	public void setUnico(byte[] unico) {
		this.unico = unico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ViajeNr", nullable = false)
	public Viajes getViajes() {
		return this.viajes;
	}

	public void setViajes(Viajes viajes) {
		this.viajes = viajes;
	}

	@Column(name = "Expreso")
	public Integer getExpreso() {
		return this.expreso;
	}

	public void setExpreso(Integer expreso) {
		this.expreso = expreso;
	}

	@Column(name = "Localidad", length = 50)
	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	@Column(name = "HoraSalida", length = 16)
	public Date getHoraSalida() {
		return this.horaSalida;
	}

	public void setHoraSalida(Date horaSalida) {
		this.horaSalida = horaSalida;
	}

	@Column(name = "HoraEntrada", length = 16)
	public Date getHoraEntrada() {
		return this.horaEntrada;
	}

	public void setHoraEntrada(Date horaEntrada) {
		this.horaEntrada = horaEntrada;
	}

	@Column(name = "Obser", length = 250)
	public String getObser() {
		return this.obser;
	}

	public void setObser(String obser) {
		this.obser = obser;
	}

	@Column(name = "NoCalcula")
	public Integer getNoCalcula() {
		return this.noCalcula;
	}

	public void setNoCalcula(Integer noCalcula) {
		this.noCalcula = noCalcula;
	}

	@Column(name = "Bultos", precision = 24, scale = 0)
	public Float getBultos() {
		return this.bultos;
	}

	public void setBultos(Float bultos) {
		this.bultos = bultos;
	}

	@Column(name = "Cant1", precision = 24, scale = 0)
	public Float getCant1() {
		return this.cant1;
	}

	public void setCant1(Float cant1) {
		this.cant1 = cant1;
	}

	@Column(name = "Cant2", precision = 24, scale = 0)
	public Float getCant2() {
		return this.cant2;
	}

	public void setCant2(Float cant2) {
		this.cant2 = cant2;
	}

	@Column(name = "Orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "NetoGrav", scale = 4)
	public BigDecimal getNetoGrav() {
		return this.netoGrav;
	}

	public void setNetoGrav(BigDecimal netoGrav) {
		this.netoGrav = netoGrav;
	}
	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transacRemito")
	public Transac getTransacRemito() {
		return transacRemito;
	}

	public void setTransacRemito(Transac transacRemito) {
		this.transacRemito = transacRemito;
	}

	
	
}
