package jmc.skweb.core.model;

// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DomiciliosId generated by hbm2java
 */
@Embeddable
public class DomiciliosId implements java.io.Serializable {

	private Integer genteNr;
	private Integer domiNr;

	public DomiciliosId() {
	}

	public DomiciliosId(Integer genteNr, Integer domiNr) {
		this.genteNr = genteNr;
		this.domiNr = domiNr;
	}

	@Column(name = "GenteNr", nullable = false)
	public Integer getGenteNr() {
		return this.genteNr;
	}

	public void setGenteNr(Integer genteNr) {
		this.genteNr = genteNr;
	}

	@Column(name = "DomiNr", nullable = false)
	public Integer getDomiNr() {
		return this.domiNr;
	}

	public void setDomiNr(Integer domiNr) {
		this.domiNr = domiNr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DomiciliosId))
			return false;
		DomiciliosId castOther = (DomiciliosId) other;

		return (this.getGenteNr() == castOther.getGenteNr())
				&& (this.getDomiNr() == castOther.getDomiNr());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getGenteNr();
		result = 37 * result + this.getDomiNr();
		return result;
	}

}
