package jmc.skweb.core.model;

// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Existencias generated by hbm2java
 */
@Entity
//@Table(name = "Existencias", schema = "ComunSql.dbo")
//Simpa
//@Table(name = "Existencias", schema = "ArtPlas.dbo")
@Table(name = "EstadiTipoReporte", schema = " ComunSql.dbo ")
public class EstadiTipoReporte implements java.io.Serializable {

	private int nr;
	private String descrip;
	private List<EstadiReporte> listEstadiReporte = new ArrayList<EstadiReporte>();
	private List<EstadiOrigen> listEstadiOrigen = new ArrayList<EstadiOrigen>();	
	
	
	@OneToMany(cascade=CascadeType.ALL,targetEntity=EstadiOrigen.class,fetch=FetchType.LAZY,mappedBy="estadiTipoReporte")
	public List<EstadiOrigen> getListEstadiOrigen() {
		return listEstadiOrigen;
	}

	public void setListEstadiOrigen(List<EstadiOrigen> listEstadiOrigen) {
		this.listEstadiOrigen = listEstadiOrigen;
	}

	@OneToMany(cascade=CascadeType.ALL,targetEntity=EstadiReporte.class,fetch=FetchType.LAZY,mappedBy="estadiTipoReporte")
	public List<EstadiReporte> getListEstadiReporte() {
		return listEstadiReporte;
	}

	public void setListEstadiReporte(List<EstadiReporte> listEstadiReporte) {
		this.listEstadiReporte = listEstadiReporte;
	}

	public EstadiTipoReporte() {
	}

	public EstadiTipoReporte(int nr) {
		this.nr = nr;
	}

	@Id
	@Column(name = "nr", unique = true, nullable = false)
	public int getNr() {
		return this.nr;
	}

	public void setNr(int nr) {
		this.nr = nr;
	}

	@Column(name = "descrip", length = 30)	
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	}
