package jmc.skweb.core.model;



// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Gente generated by hbm2java
 */
@Entity
@Table(name = "Gente", schema = "ComunSql.dbo				")
public class Gente implements java.io.Serializable {

	private Integer genteNr;
	private String razonSocial;
	private Date fechaIngreso;
	private Integer relacion;
	private Short cliente;
	private Short proveed;
	private String observacion;
	private String cuit;
	private Integer provNr;
	private Integer zonaNr;
	private Integer vendedorNr;
	private Integer cobradorNr;
	private Integer condVta;
	private Float comisVta;
	private Float comisCob;
	//private Integer tipoIva;
	private Impuestos impuestos;
	private BigDecimal credCta;
	private BigDecimal credCheques;
	private Short noFactura;
	private Short marcado1;
	private Short marcado2;
	private Short marcado3;
	private Short activGrav;
	private Integer nrAnterior;
	private String proveedorNr;
	private Integer codImpuCont;
	private Short percibeIb;
	private Short percibeIva;
	private Float bonifStd;
	private String nrIngBru;
	private Integer listaPrecio;
	private Domicilios domicilioPricipal;
	private String descripC;
	private Integer idRol;
	
	
	
	@Transient
	public String getDescripC() {
		this.descripC = "[" + genteNr + "] " + razonSocial; 
		return descripC;
	}






	public void setDescripC(String descripC) {
		this.descripC = descripC;
	}






	public Gente() {
	}

	
	



	public Gente(Integer genteNr, Integer relacion, Short cliente, Short proveed,
			Integer provNr, Integer zonaNr, Integer vendedorNr, Integer cobradorNr,
			Integer condVta, Float comisVta, Float comisCob, Integer tipoIva,
			BigDecimal credCta, BigDecimal credCheques, Short noFactura,
			Short marcado1, Short marcado2, Short marcado3, Short activGrav,
			Integer codImpuCont, Short percibeIb, Short percibeIva, Float bonifStd,
			Integer listaPrecio) {
		this.genteNr = genteNr;
		this.relacion = relacion;
		this.cliente = cliente;
		this.proveed = proveed;
		this.provNr = provNr;
		this.zonaNr = zonaNr;
		this.vendedorNr = vendedorNr;
		this.cobradorNr = cobradorNr;
		this.condVta = condVta;
		this.comisVta = comisVta;
		this.comisCob = comisCob;
		//this.tipoIva = tipoIva;
		this.credCta = credCta;
		this.credCheques = credCheques;
		this.noFactura = noFactura;
		this.marcado1 = marcado1;
		this.marcado2 = marcado2;
		this.marcado3 = marcado3;
		this.activGrav = activGrav;
		this.codImpuCont = codImpuCont;
		this.percibeIb = percibeIb;
		this.percibeIva = percibeIva;
		this.bonifStd = bonifStd;
		this.listaPrecio = listaPrecio;
	}

	public Gente(Integer genteNr, String razonSocial, Date fechaIngreso,
			Integer relacion, Short cliente, Short proveed, String observacion,
			String cuit, Integer provNr, Integer zonaNr, Integer vendedorNr,
			Integer cobradorNr, Integer condVta, Float comisVta, Float comisCob,
			Integer tipoIva, BigDecimal credCta, BigDecimal credCheques,
			Short noFactura, Short marcado1, Short marcado2, Short marcado3,
			Short activGrav, Integer nrAnterior, String proveedorNr,
			Integer codImpuCont, Short percibeIb, Short percibeIva, Float bonifStd,
			String nrIngBru, Integer listaPrecio, Set domicilioses) {
		this.genteNr = genteNr;
		this.razonSocial = razonSocial;
		this.fechaIngreso = fechaIngreso;
		this.relacion = relacion;
		this.cliente = cliente;
		this.proveed = proveed;
		this.observacion = observacion;
		this.cuit = cuit;
		this.provNr = provNr;
		this.zonaNr = zonaNr;
		this.vendedorNr = vendedorNr;
		this.cobradorNr = cobradorNr;
		this.condVta = condVta;
		this.comisVta = comisVta;
		this.comisCob = comisCob;
		//this.tipoIva = tipoIva;
		this.credCta = credCta;
		this.credCheques = credCheques;
		this.noFactura = noFactura;
		this.marcado1 = marcado1;
		this.marcado2 = marcado2;
		this.marcado3 = marcado3;
		this.activGrav = activGrav;
		this.nrAnterior = nrAnterior;
		this.proveedorNr = proveedorNr;
		this.codImpuCont = codImpuCont;
		this.percibeIb = percibeIb;
		this.percibeIva = percibeIva;
		this.bonifStd = bonifStd;
		this.nrIngBru = nrIngBru;
		this.listaPrecio = listaPrecio;
	
	}

	@Id
	@Column(name = "GenteNr", unique = true, nullable = false)
	public Integer getGenteNr() {
		return this.genteNr;
	}

	public void setGenteNr(Integer genteNr) {
		this.genteNr = genteNr;
	}

	@Column(name = "\"Razon Social\"", length = 50, nullable = true)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	@Column(name = "\"Fecha Ingreso\"", length = 16, nullable = true)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "Relacion", nullable = true)
	public Integer getRelacion() {
		return this.relacion;
	}

	public void setRelacion(Integer relacion) {
		this.relacion = relacion;
	}

	@Column(name = "Cliente", nullable = true)
	public Short getCliente() {
		return this.cliente;
	}

	public void setCliente(Short cliente) {
		this.cliente = cliente;
	}

	@Column(name = "Proveed", nullable = true)
	public Short getProveed() {
		return this.proveed;
	}

	public void setProveed(Short proveed) {
		this.proveed = proveed;
	}

	@Column(name = "Observacion", nullable = true)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "Cuit", length = 15, nullable = true)
	public String getCuit() {
		return this.cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}

	@Column(name = "ProvNr", nullable = true)
	public Integer getProvNr() {
		return this.provNr;
	}

	public void setProvNr(Integer provNr) {
		this.provNr = provNr;
	}

	@Column(name = "ZonaNr", nullable = true)
	public Integer getZonaNr() {
		return this.zonaNr;
	}

	public void setZonaNr(Integer zonaNr) {
		this.zonaNr = zonaNr;
	}

	@Column(name = "VendedorNr", nullable = true)
	public Integer getVendedorNr() {
		return this.vendedorNr;
	}

	public void setVendedorNr(Integer vendedorNr) {
		this.vendedorNr = vendedorNr;
	}

	@Column(name = "CobradorNr", nullable = true)
	public Integer getCobradorNr() {
		return this.cobradorNr;
	}

	public void setCobradorNr(Integer cobradorNr) {
		this.cobradorNr = cobradorNr;
	}

	@Column(name = "CondVta", nullable = true)
	public Integer getCondVta() {
		return this.condVta;
	}

	public void setCondVta(Integer condVta) {
		this.condVta = condVta;
	}

	@Column(name = "ComisVta", nullable = true, precision = 24, scale = 0)
	public Float getComisVta() {
		return this.comisVta;
	}

	public void setComisVta(Float comisVta) {
		this.comisVta = comisVta;
	}

	@Column(name = "ComisCob", nullable = true, precision = 24, scale = 0)
	public Float getComisCob() {
		return this.comisCob;
	}

	public void setComisCob(Float comisCob) {
		this.comisCob = comisCob;
	}
	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TipoIva")
	public Impuestos getImpuestos() {
		return impuestos;
	}

	public void setImpuestos(Impuestos impuestos) {
		this.impuestos = impuestos;
	}

	
	@Column(name = "CredCta", nullable = true, scale = 4)
	public BigDecimal getCredCta() {
		return this.credCta;
	}

	public void setCredCta(BigDecimal credCta) {
		this.credCta = credCta;
	}

	@Column(name = "CredCheques", nullable = true, scale = 4)
	public BigDecimal getCredCheques() {
		return this.credCheques;
	}

	public void setCredCheques(BigDecimal credCheques) {
		this.credCheques = credCheques;
	}

	@Column(name = "NoFactura", nullable = true)
	public Short getNoFactura() {
		return this.noFactura;
	}

	public void setNoFactura(Short noFactura) {
		this.noFactura = noFactura;
	}

	@Column(name = "Marcado1", nullable = true)
	public Short getMarcado1() {
		return this.marcado1;
	}

	public void setMarcado1(Short marcado1) {
		this.marcado1 = marcado1;
	}

	@Column(name = "Marcado2", nullable = true)
	public Short getMarcado2() {
		return this.marcado2;
	}

	public void setMarcado2(Short marcado2) {
		this.marcado2 = marcado2;
	}

	@Column(name = "Marcado3", nullable = true)
	public Short getMarcado3() {
		return this.marcado3;
	}

	public void setMarcado3(Short marcado3) {
		this.marcado3 = marcado3;
	}

	@Column(name = "ActivGrav", nullable = true)
	public Short getActivGrav() {
		return this.activGrav;
	}

	public void setActivGrav(Short activGrav) {
		this.activGrav = activGrav;
	}

	@Column(name = "NrAnterior")
	public Integer getNrAnterior() {
		return this.nrAnterior;
	}

	public void setNrAnterior(Integer nrAnterior) {
		this.nrAnterior = nrAnterior;
	}

	@Column(name = "ProveedorNr", length = 15)
	public String getProveedorNr() {
		return this.proveedorNr;
	}

	public void setProveedorNr(String proveedorNr) {
		this.proveedorNr = proveedorNr;
	}

	@Column(name = "CodImpuCont", nullable = true)
	public Integer getCodImpuCont() {
		return this.codImpuCont;
	}

	public void setCodImpuCont(Integer codImpuCont) {
		this.codImpuCont = codImpuCont;
	}

	@Column(name = "PercibeIb", nullable = true)
	public Short getPercibeIb() {
		return this.percibeIb;
	}

	public void setPercibeIb(Short percibeIb) {
		this.percibeIb = percibeIb;
	}

	@Column(name = "PercibeIva", nullable = true)
	public Short getPercibeIva() {
		return this.percibeIva;
	}

	public void setPercibeIva(Short percibeIva) {
		this.percibeIva = percibeIva;
	}

	@Column(name = "BonifStd", nullable = true, precision = 24, scale = 0)
	public Float getBonifStd() {
		return this.bonifStd;
	}

	public void setBonifStd(Float bonifStd) {
		this.bonifStd = bonifStd;
	}

	@Column(name = "NrIngBru", length = 13)
	public String getNrIngBru() {
		return this.nrIngBru;
	}

	public void setNrIngBru(String nrIngBru) {
		this.nrIngBru = nrIngBru;
	}

	@Column(name = "ListaPrecio", nullable = true)
	public Integer getListaPrecio() {
		return this.listaPrecio;
	}

	public void setListaPrecio(Integer listaPrecio) {
		this.listaPrecio = listaPrecio;
	}






	@Transient
	public Domicilios getDomicilioPricipal() {
		return domicilioPricipal;
	}

	public void setDomicilioPricipal(Domicilios domicilioPricipal) {
		this.domicilioPricipal = domicilioPricipal;
	}





	@Transient
	public Integer getIdRol() {
		return idRol;
	}






	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	


	
	
}

