package jmc.skweb.core.model;

// Generated 22/09/2011 00:18:30 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import jmc.skweb.util.DateUtil;
import jmc.skweb.util.MathUtil;

/**
 * Paseban generated by hbm2java
 */
@Entity
//@Table(name = "Paseban", schema = "Empresa1.dbo")
@Table(name = "Paseban", schema = "Empresa1.dbo")
public class Paseban implements java.io.Serializable {

	private Integer transacNr;
	private Integer cajaNr;
	private Integer tipoMov;
	private Date fecha;
	private Date fechaContable;
	private Date fechaIngreso;
	private Date fechaConciliacion;
	private BigDecimal importe;
	private String observaciones;
	private Integer impuCont;
	private Integer transacOrdPago;
	private Integer transacOrigen;
	private Integer operNr;
	private Short marcaBaja;
	private Integer chePropioNr;
	private Integer nrInt;
	private Integer destino;
	private String serieNr;
	private String cuentaNr;
	private Short clearing;
	private Date fechaPasDest;
	private Integer instituNr;
	private Short bancoSucursal;
	private Integer nrSucursal;
	private Short rechazado;
	private Short cobrado;
	private Integer genteNr;
	private String objetoOle;
	private Short tipoBoleta;
	private Integer otraRef;
	private Short terDirec;
	private Short rescatado;
	private String cuit;

	public Paseban() {
	}

	public Paseban(Integer transacNr, Integer cajaNr, Integer tipoMov, Date fecha,
			Date fechaContable, Date fechaIngreso, BigDecimal importe,
			Integer impuCont, Integer transacOrdPago, Integer transacOrigen, Integer operNr) {
		this.transacNr = transacNr;
		this.cajaNr = cajaNr;
		this.tipoMov = tipoMov;
		this.fecha = fecha;
		this.fechaContable = fechaContable;
		this.fechaIngreso = fechaIngreso;
		this.importe = importe;
		this.impuCont = impuCont;
		this.transacOrdPago = transacOrdPago;
		this.transacOrigen = transacOrigen;
		this.operNr = operNr;
	}

	public Paseban(Integer transacNr, Integer cajaNr, Integer tipoMov, Date fecha,
			Date fechaContable, Date fechaIngreso, Date fechaConciliacion,
			BigDecimal importe, String observaciones, Integer impuCont,
			Integer transacOrdPago, Integer transacOrigen, Integer operNr, Short marcaBaja,
			Integer chePropioNr, Integer nrInt, Integer destino,
			String serieNr, String cuentaNr, Short clearing, Date fechaPasDest,
			Integer instituNr, Short bancoSucursal, Integer nrSucursal,
			Short rechazado, Short cobrado, Integer genteNr, String objetoOle,
			Short tipoBoleta, Integer otraRef, Short terDirec, Short rescatado,
			String cuit) {
		this.transacNr = transacNr;
		this.cajaNr = cajaNr;
		this.tipoMov = tipoMov;
		this.fecha = fecha;
		this.fechaContable = fechaContable;
		this.fechaIngreso = fechaIngreso;
		this.fechaConciliacion = fechaConciliacion;
		this.importe = importe;
		this.observaciones = observaciones;
		this.impuCont = impuCont;
		this.transacOrdPago = transacOrdPago;
		this.transacOrigen = transacOrigen;
		this.operNr = operNr;
		this.marcaBaja = marcaBaja;
		this.chePropioNr = chePropioNr;
		this.nrInt = nrInt;
		this.destino = destino;
		this.serieNr = serieNr;
		this.cuentaNr = cuentaNr;
		this.clearing = clearing;
		this.fechaPasDest = fechaPasDest;
		this.instituNr = instituNr;
		this.bancoSucursal = bancoSucursal;
		this.nrSucursal = nrSucursal;
		this.rechazado = rechazado;
		this.cobrado = cobrado;
		this.genteNr = genteNr;
		this.objetoOle = objetoOle;
		this.tipoBoleta = tipoBoleta;
		this.otraRef = otraRef;
		this.terDirec = terDirec;
		this.rescatado = rescatado;
		this.cuit = cuit;
	}

	@Id
	@Column(name = "TransacNr", unique = true, nullable = false)
	public Integer getTransacNr() {
		return this.transacNr;
	}

	public void setTransacNr(Integer transacNr) {
		this.transacNr = transacNr;
	}

	@Column(name = "CajaNr", nullable = false)
	public Integer getCajaNr() {
		return this.cajaNr;
	}

	public void setCajaNr(Integer cajaNr) {
		this.cajaNr = cajaNr;
	}

	@Column(name = "TipoMov", nullable = false)
	public Integer getTipoMov() {
		return this.tipoMov;
	}

	public void setTipoMov(Integer tipoMov) {
		this.tipoMov = tipoMov;
	}

	@Column(name = "Fecha", nullable = false, length = 16)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "FechaContable", nullable = false, length = 16)
	public Date getFechaContable() {
		return this.fechaContable;
	}

	public void setFechaContable(Date fechaContable) {
		this.fechaContable = fechaContable;
	}

	@Column(name = "FechaIngreso", nullable = false, length = 16)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "FechaConciliacion", length = 16)
	public Date getFechaConciliacion() {
		return this.fechaConciliacion;
	}

	public void setFechaConciliacion(Date fechaConciliacion) {
		this.fechaConciliacion = fechaConciliacion;
	}

	@Column(name = "Importe", nullable = false, scale = 4)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "Observaciones", length = 50)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "ImpuCont", nullable = false)
	public Integer getImpuCont() {
		return this.impuCont;
	}

	public void setImpuCont(Integer impuCont) {
		this.impuCont = impuCont;
	}

	@Column(name = "TransacOrdPago", nullable = false)
	public Integer getTransacOrdPago() {
		return this.transacOrdPago;
	}

	public void setTransacOrdPago(Integer transacOrdPago) {
		this.transacOrdPago = transacOrdPago;
	}

	@Column(name = "TransacOrigen", nullable = false)
	public Integer getTransacOrigen() {
		return this.transacOrigen;
	}

	public void setTransacOrigen(Integer transacOrigen) {
		this.transacOrigen = transacOrigen;
	}

	@Column(name = "OperNr", nullable = false)
	public Integer getOperNr() {
		return this.operNr;
	}

	public void setOperNr(Integer operNr) {
		this.operNr = operNr;
	}

	@Column(name = "MarcaBaja")
	public Short getMarcaBaja() {
		return this.marcaBaja;
	}

	public void setMarcaBaja(Short marcaBaja) {
		this.marcaBaja = marcaBaja;
	}

	@Column(name = "ChePropioNr")
	public Integer getChePropioNr() {
		return this.chePropioNr;
	}

	public void setChePropioNr(Integer chePropioNr) {
		this.chePropioNr = chePropioNr;
	}

	@Column(name = "NrInt")
	public Integer getNrInt() {
		return this.nrInt;
	}

	public void setNrInt(Integer nrInt) {
		this.nrInt = nrInt;
	}

	@Column(name = "Destino")
	public Integer getDestino() {
		return this.destino;
	}

	public void setDestino(Integer destino) {
		this.destino = destino;
	}

	@Column(name = "SerieNr", length = 15)
	public String getSerieNr() {
		return this.serieNr;
	}

	public void setSerieNr(String serieNr) {
		this.serieNr = serieNr;
	}

	@Column(name = "CuentaNr", length = 15)
	public String getCuentaNr() {
		return this.cuentaNr;
	}

	public void setCuentaNr(String cuentaNr) {
		this.cuentaNr = cuentaNr;
	}

	@Column(name = "Clearing")
	public Short getClearing() {
		return this.clearing;
	}

	public void setClearing(Short clearing) {
		this.clearing = clearing;
	}

	@Column(name = "FechaPasDest", length = 16)
	public Date getFechaPasDest() {
		return this.fechaPasDest;
	}

	public void setFechaPasDest(Date fechaPasDest) {
		this.fechaPasDest = fechaPasDest;
	}

	@Column(name = "InstituNr")
	public Integer getInstituNr() {
		return this.instituNr;
	}

	public void setInstituNr(Integer instituNr) {
		this.instituNr = instituNr;
	}

	@Column(name = "BancoSucursal")
	public Short getBancoSucursal() {
		return this.bancoSucursal;
	}

	public void setBancoSucursal(Short bancoSucursal) {
		this.bancoSucursal = bancoSucursal;
	}

	@Column(name = "NrSucursal")
	public Integer getNrSucursal() {
		return this.nrSucursal;
	}

	public void setNrSucursal(Integer nrSucursal) {
		this.nrSucursal = nrSucursal;
	}

	@Column(name = "Rechazado")
	public Short getRechazado() {
		return this.rechazado;
	}

	public void setRechazado(Short rechazado) {
		this.rechazado = rechazado;
	}

	@Column(name = "Cobrado")
	public Short getCobrado() {
		return this.cobrado;
	}

	public void setCobrado(Short cobrado) {
		this.cobrado = cobrado;
	}

	@Column(name = "GenteNr")
	public Integer getGenteNr() {
		return this.genteNr;
	}

	public void setGenteNr(Integer genteNr) {
		this.genteNr = genteNr;
	}

	@Column(name = "ObjetoOle", length = 1)
	public String getObjetoOle() {
		return this.objetoOle;
	}

	public void setObjetoOle(String objetoOle) {
		this.objetoOle = objetoOle;
	}

	@Column(name = "TipoBoleta")
	public Short getTipoBoleta() {
		return this.tipoBoleta;
	}

	public void setTipoBoleta(Short tipoBoleta) {
		this.tipoBoleta = tipoBoleta;
	}

	@Column(name = "OtraRef")
	public Integer getOtraRef() {
		return this.otraRef;
	}

	public void setOtraRef(Integer otraRef) {
		this.otraRef = otraRef;
	}

	@Column(name = "TerDirec")
	public Short getTerDirec() {
		return this.terDirec;
	}

	public void setTerDirec(Short terDirec) {
		this.terDirec = terDirec;
	}

	@Column(name = "Rescatado")
	public Short getRescatado() {
		return this.rescatado;
	}

	public void setRescatado(Short rescatado) {
		this.rescatado = rescatado;
	}

	@Column(name = "Cuit", length = 15)
	public String getCuit() {
		return this.cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}

	@Transient
	public String getformattedDate() {
		String fechaComp = null;
		if (this.fecha != null)
			fechaComp = DateUtil.getFormatedSTDDate(new Timestamp(this.fecha.getTime()));
		return fechaComp;
	}

	@Transient
	public Double getImporteCalculado() {
		return MathUtil.redondear(importe.doubleValue());
	}

}
