package jmc.skweb.core.model.shortEntities;



// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Gente generated by hbm2java
 */
@Entity
@Table(name = "Gente", schema = "ComunSql.dbo")
public class GenteBasic implements java.io.Serializable {

	private Integer genteNr;
	private String razonSocial;
	private Integer vendedorNr;
	private String descripC;
		
	
	public GenteBasic() {
	}

	@Id
	@Column(name = "GenteNr", unique = true, nullable = false)
	public Integer getGenteNr() {
		return genteNr;
	}
	public void setGenteNr(Integer genteNr) {
		this.genteNr = genteNr;
	}

	@Column(name = "\"Razon Social\"", length = 50, nullable = true)
	public String getRazonSocial() {
		return razonSocial;
	}
	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}
	
	@Column(name = "VendedorNr", nullable = true)
	public Integer getVendedorNr() {
		return this.vendedorNr;
	}

	public void setVendedorNr(Integer vendedorNr) {
		this.vendedorNr = vendedorNr;
	}


	@Transient
	public String getDescripC() {
		this.descripC = "[" + genteNr + "] " + razonSocial; 
		return descripC;
	}






	public void setDescripC(String descripC) {
		this.descripC = descripC;
	}
}

