package jmc.skweb.core.model;

// Generated 23/09/2011 12:11:03 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Existencias generated by hbm2java
 */
@Entity
//@Table(name = "Existencias", schema = "ComunSql.dbo")
//Simpa
//@Table(name = "Existencias", schema = "ArtPlas.dbo")
@Table(name = "EstadiOrigen", schema = " ComunSql.dbo ")
public class EstadiOrigen implements java.io.Serializable {

	private int nr;
	private String descrip;
	private EstadiTipoReporte estadiTipoReporte;
	
	
	@ManyToOne(fetch = FetchType.LAZY )
	@JoinColumn(name = "nrTipoReporte", nullable = false)
	public EstadiTipoReporte getEstadiTipoReporte() {
		return estadiTipoReporte;
	}

	public void setEstadiTipoReporte(EstadiTipoReporte estadiTipoReporte) {
		this.estadiTipoReporte = estadiTipoReporte;
	}

	
	public EstadiOrigen() {
	}

	public EstadiOrigen(int nr) {
		this.nr = nr;
	}

	@Id
	@Column(name = "nr")
	public int getNr() {
		return this.nr;
	}

	public void setNr(int nr) {
		this.nr = nr;
	}

	@Column(name = "descrip", length = 30)	
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	}
